package arrays.models;

public class MelonData {
	public static Melon[] dataForMelons() {
		return new Melon[] {
			new Melon("Type I", 50),
			new Melon("Type II", 60),
			new Melon("Type III", 70),
			new Melon("Type IV", 80),
			new Melon("Type V", 90),
			new Melon("Type VI", 100),
			new Melon("Type X", 110),
			new Melon("Type L", 120),
			new Melon("Type S", 130),
			new Melon("Type M", 140),
			new Melon("Type Q", 150),
			new Melon("Type W", 160),
			new Melon("Type I", 60),
			new Melon("Type II", 70),
			new Melon("Type III", 80),
			new Melon("Type IV", 90),
			new Melon("Type V", 100),
			new Melon("Type VI", 110),
			new Melon("Type X", 120),
			new Melon("Type L", 130),
			new Melon("Type S", 140),
			new Melon("Type M", 150),
			new Melon("Type Q", 160),
			new Melon("Type W", 170),
			new Melon("Type I", 70),
			new Melon("Type II", 80),
			new Melon("Type III", 90),
			new Melon("Type IV", 100),
			new Melon("Type V", 110),
			new Melon("Type VI", 120),
			new Melon("Type X", 130),
			new Melon("Type L", 140),
			new Melon("Type S", 150),
			new Melon("Type M", 160),
			new Melon("Type Q", 170),
			new Melon("Type W", 180),
			new Melon("Type I", 80),
			new Melon("Type II", 90),
			new Melon("Type III", 100),
			new Melon("Type IV", 110),
			new Melon("Type V", 120),
			new Melon("Type VI", 130),
			new Melon("Type X", 140),
			new Melon("Type L", 150),
			new Melon("Type S", 160),
			new Melon("Type M", 170),
			new Melon("Type Q", 180),
			new Melon("Type W", 190)
		};
	}
}
